name: Prevent Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prevent-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR cannot be merged."
          exit 1
